# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-02 07:44
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('details', models.TextField()),
                ('public_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('gonghao', models.CharField(max_length=200, unique=True)),
                ('depth', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('permission', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qiandao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('gonghao', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField()),
                ('first_qiandao', models.CharField(max_length=200)),
                ('second_qiandao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Qingjia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonghao', models.CharField(max_length=200, unique=True)),
                ('from_date', models.CharField(max_length=200)),
                ('to_date', models.CharField(max_length=200)),
                ('now_date', models.CharField(default=datetime.date(2017, 5, 2), max_length=200)),
                ('cause', models.CharField(max_length=200)),
                ('approve_result', models.CharField(max_length=200)),
                ('refuse_reason', models.CharField(max_length=200)),
                ('approve_person', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonghao', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('depth', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('base_salary', models.CharField(max_length=200)),
                ('ti_cheng', models.CharField(max_length=200)),
                ('jiaban', models.CharField(default=0, max_length=200)),
                ('queqing', models.CharField(default=0, max_length=200)),
                ('tiaoxiu', models.CharField(default=0, max_length=200)),
                ('qingjia', models.CharField(default=0, max_length=200)),
                ('jiaban_hour', models.CharField(default=0, max_length=200)),
                ('queqing_hour', models.CharField(default=0, max_length=200)),
                ('tiaoxiu_hour', models.CharField(default=0, max_length=200)),
                ('qingjia_hour', models.CharField(default=0, max_length=200)),
                ('jiangjin', models.CharField(max_length=200)),
                ('total_salary', models.CharField(max_length=200)),
                ('mouth_time', models.CharField(default=0, max_length=200)),
            ],
        ),
    ]
