# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-06 05:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AMS', '0002_auto_20170502_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base_salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('base_salary', models.CharField(max_length=200)),
                ('jiaban', models.CharField(default=0, max_length=200)),
                ('queqing', models.CharField(default=0, max_length=200)),
                ('qingjia', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='qingjia',
            name='now_date',
            field=models.CharField(default=datetime.date(2017, 5, 6), max_length=200),
        ),
    ]
